export const ADD_CATEGORIE_TO_USER = "ADD_CATEGORIE_TO_USER";
export const REMOVE_CATEGORIE_FROM_USER = "REMOVE_CATEGORIE_FROM_USER";
export const CLEAR_CATEGORIES_FROM_USER = "CLEAR_CATEGORIES_FROM_USER";

export const SETCURRENT_USER = "SETCURRENT_USER";
export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";

export const UPDATE_OPTION = "UPDATE_OPTION";
export const RESET_OPTION = "RESET_OPTION";
