let _IMAGES ={"aliments":[{"path": require("language_therapy/ressources/mot-image/aliments/abricot.jpg"),
                "fr": "abricot",
                "ar": "مشمش"
              },{"path": require("language_therapy/ressources/mot-image/aliments/ail.jpg"),
                "fr": "ail",
                "ar": "ثوم"
              },{"path": require("language_therapy/ressources/mot-image/aliments/amande.jpg"),
                "fr": "amande",
                "ar": "لوز"
              },{"path": require("language_therapy/ressources/mot-image/aliments/ananas.jpg"),
                "fr": "ananas",
                "ar": "أناناس"
              },{"path": require("language_therapy/ressources/mot-image/aliments/aubergine.jpg"),
                "fr": "aubergine",
                "ar": "باذنجان"
              },{"path": require("language_therapy/ressources/mot-image/aliments/baguette.jpg"),
                "fr": "baguette",
                "ar": "خبز"
              },{"path": require("language_therapy/ressources/mot-image/aliments/banane.jpg"),
                "fr": "banane",
                "ar": "موز"
              },{"path": require("language_therapy/ressources/mot-image/aliments/beurre.jpg"),
                "fr": "beurre",
                "ar": "زبدة"
              },{"path": require("language_therapy/ressources/mot-image/aliments/carotte.jpg"),
                "fr": "carotte",
                "ar": "جزرة"
              },{"path": require("language_therapy/ressources/mot-image/aliments/cerise.jpg"),
                "fr": "cerise",
                "ar": "الكرز"
              },{"path": require("language_therapy/ressources/mot-image/aliments/champignon.jpg"),
                "fr": "champignon",
                "ar": "فطر"
              },{"path": require("language_therapy/ressources/mot-image/aliments/chocolat.jpg"),
                "fr": "chocolat",
                "ar": "شوكولا"
              },{"path": require("language_therapy/ressources/mot-image/aliments/choux_fleur.jpg"),
                "fr": "choux fleur",
                "ar": "ملفوف"
              },{"path": require("language_therapy/ressources/mot-image/aliments/citron.jpg"),
                "fr": "citron",
                "ar": "ليمون"
              },{"path": require("language_therapy/ressources/mot-image/aliments/courgette.jpg"),
                "fr": "courgette",
                "ar": "كوسا"
              },{"path": require("language_therapy/ressources/mot-image/aliments/figue.jpg"),
                "fr": "figue",
                "ar": "تين"
              },{"path": require("language_therapy/ressources/mot-image/aliments/fraise.jpg"),
                "fr": "fraise",
                "ar": "فراولة"
              },{"path": require("language_therapy/ressources/mot-image/aliments/grenade.jpg"),
                "fr": "grenade",
                "ar": "رمان"
              },{"path": require("language_therapy/ressources/mot-image/aliments/haricot_vert.jpg"),
                "fr": "haricot vert",
                "ar": "الفاصوليا"
              },{"path": require("language_therapy/ressources/mot-image/aliments/miel.jpg"),
                "fr": "miel",
                "ar": "عسل"
              },{"path": require("language_therapy/ressources/mot-image/aliments/noix.jpg"),
                "fr": "noix",
                "ar": "جوز"
              },{"path": require("language_therapy/ressources/mot-image/aliments/oeuf.jpg"),
                "fr": "oeuf",
                "ar": "بيضة"
              },{"path": require("language_therapy/ressources/mot-image/aliments/oignon.jpg"),
                "fr": "oignon",
                "ar": "بصل"
              },{"path": require("language_therapy/ressources/mot-image/aliments/orange.jpg"),
                "fr": "orange",
                "ar": "برتقال"
              },{"path": require("language_therapy/ressources/mot-image/aliments/pastèque.jpg"),
                "fr": "pastèque",
                "ar": "بطيخ"
              },{"path": require("language_therapy/ressources/mot-image/aliments/pates.jpg"),
                "fr": "pates",
                "ar": "معكرونة"
              },{"path": require("language_therapy/ressources/mot-image/aliments/poire.jpg"),
                "fr": "poire",
                "ar": "اجاصة"
              },{"path": require("language_therapy/ressources/mot-image/aliments/poivron.jpg"),
                "fr": "poivron",
                "ar": "فلفل حلو"
              },{"path": require("language_therapy/ressources/mot-image/aliments/pomme.jpg"),
                "fr": "pomme",
                "ar": "تفاح"
              },{"path": require("language_therapy/ressources/mot-image/aliments/pomme_de_terre.jpg"),
                "fr": "pomme de terre",
                "ar": "بطاطا"
              },{"path": require("language_therapy/ressources/mot-image/aliments/radis.jpg"),
                "fr": "radis",
                "ar": "فجل"
              },{"path": require("language_therapy/ressources/mot-image/aliments/raisin.jpg"),
                "fr": "raisin",
                "ar": "عنب"
              },{"path": require("language_therapy/ressources/mot-image/aliments/riz.jpg"),
                "fr": "riz",
                "ar": "الرز"
              },{"path": require("language_therapy/ressources/mot-image/aliments/tomate.jpg"),
                "fr": "tomate",
                "ar": "بندورة"
              }],"animaux":[{"path": require("language_therapy/ressources/mot-image/animaux/canard.jpg"),
                "fr": "canard",
                "ar": "بطة"
              },{"path": require("language_therapy/ressources/mot-image/animaux/chat.jpg"),
                "fr": "chat",
                "ar": "قطة"
              },{"path": require("language_therapy/ressources/mot-image/animaux/cheval.jpg"),
                "fr": "cheval",
                "ar": "حصان"
              },{"path": require("language_therapy/ressources/mot-image/animaux/chien.jpg"),
                "fr": "chien",
                "ar": "كلب"
              },{"path": require("language_therapy/ressources/mot-image/animaux/chèvre.jpg"),
                "fr": "chèvre",
                "ar": "معزاة"
              },{"path": require("language_therapy/ressources/mot-image/animaux/colombe.jpg"),
                "fr": "colombe",
                "ar": "حمام"
              },{"path": require("language_therapy/ressources/mot-image/animaux/crocodile.jpg"),
                "fr": "crocodile",
                "ar": "تمساح"
              },{"path": require("language_therapy/ressources/mot-image/animaux/cygne.jpg"),
                "fr": "cygne",
                "ar": "وزة"
              },{"path": require("language_therapy/ressources/mot-image/animaux/girafe.jpg"),
                "fr": "girafe",
                "ar": "زرافة"
              },{"path": require("language_therapy/ressources/mot-image/animaux/lapin.jpg"),
                "fr": "lapin",
                "ar": "أرنب"
              },{"path": require("language_therapy/ressources/mot-image/animaux/lion.jpg"),
                "fr": "lion",
                "ar": "اسد"
              },{"path": require("language_therapy/ressources/mot-image/animaux/loup.jpg"),
                "fr": "loup",
                "ar": "ذئب"
              },{"path": require("language_therapy/ressources/mot-image/animaux/lézard.jpg"),
                "fr": "lézard",
                "ar": "حرباء"
              },{"path": require("language_therapy/ressources/mot-image/animaux/mouton.jpg"),
                "fr": "mouton",
                "ar": "خاروف"
              },{"path": require("language_therapy/ressources/mot-image/animaux/ours.jpg"),
                "fr": "ours",
                "ar": "دب"
              },{"path": require("language_therapy/ressources/mot-image/animaux/pingouin.jpg"),
                "fr": "pingouin",
                "ar": "بطريق"
              },{"path": require("language_therapy/ressources/mot-image/animaux/poisson_rouge.jpg"),
                "fr": "poisson rouge",
                "ar": "سمكة حمراء"
              },{"path": require("language_therapy/ressources/mot-image/animaux/poule.jpg"),
                "fr": "poule",
                "ar": "دجاجة"
              },{"path": require("language_therapy/ressources/mot-image/animaux/serpent.jpg"),
                "fr": "serpent",
                "ar": "أفعى"
              },{"path": require("language_therapy/ressources/mot-image/animaux/souris.jpg"),
                "fr": "souris",
                "ar": "فأر"
              },{"path": require("language_therapy/ressources/mot-image/animaux/tigre.jpg"),
                "fr": "tigre",
                "ar": "نمر"
              },{"path": require("language_therapy/ressources/mot-image/animaux/vache.jpg"),
                "fr": "vache",
                "ar": "بقرة"
              },{"path": require("language_therapy/ressources/mot-image/animaux/éléphant.jpg"),
                "fr": "éléphant",
                "ar": "فيل"
              }],"autre":[{"path": require("language_therapy/ressources/mot-image/autre/allumette.jpg"),
                "fr": "allumette",
                "ar": "كبريتة"
              },{"path": require("language_therapy/ressources/mot-image/autre/arbre.jpg"),
                "fr": "arbre",
                "ar": "شجره"
              },{"path": require("language_therapy/ressources/mot-image/autre/aspirateur.jpg"),
                "fr": "aspirateur",
                "ar": "مكنسة كهربائية"
              },{"path": require("language_therapy/ressources/mot-image/autre/assiette.jpg"),
                "fr": "assiette",
                "ar": "صحن"
              },{"path": require("language_therapy/ressources/mot-image/autre/avion.jpg"),
                "fr": "avion",
                "ar": "طائرة"
              },{"path": require("language_therapy/ressources/mot-image/autre/bague.jpg"),
                "fr": "bague",
                "ar": "خاتم"
              },{"path": require("language_therapy/ressources/mot-image/autre/balai.jpg"),
                "fr": "balai",
                "ar": "مكنسة"
              },{"path": require("language_therapy/ressources/mot-image/autre/balançoire.jpg"),
                "fr": "balançoire",
                "ar": "أرجوحة"
              },{"path": require("language_therapy/ressources/mot-image/autre/ballon.jpg"),
                "fr": "ballon",
                "ar": "كرة"
              },{"path": require("language_therapy/ressources/mot-image/autre/bateau.jpg"),
                "fr": "bateau",
                "ar": "قارب"
              },{"path": require("language_therapy/ressources/mot-image/autre/bonnet.jpg"),
                "fr": "bonnet",
                "ar": "قبعة"
              },{"path": require("language_therapy/ressources/mot-image/autre/bouteille.jpg"),
                "fr": "bouteille",
                "ar": "زجاجة"
              },{"path": require("language_therapy/ressources/mot-image/autre/boîte.jpg"),
                "fr": "boîte",
                "ar": "ساعة"
              },{"path": require("language_therapy/ressources/mot-image/autre/briquet.jpg"),
                "fr": "briquet",
                "ar": "ولاعة"
              },{"path": require("language_therapy/ressources/mot-image/autre/brosse_à_dent.jpg"),
                "fr": "brosse à dent",
                "ar": "فرشاة أسنان"
              },{"path": require("language_therapy/ressources/mot-image/autre/bus.jpg"),
                "fr": "bus",
                "ar": "الباص"
              },{"path": require("language_therapy/ressources/mot-image/autre/café.jpg"),
                "fr": "café",
                "ar": "قهوة"
              },{"path": require("language_therapy/ressources/mot-image/autre/camion.jpg"),
                "fr": "camion",
                "ar": "شاحنة"
              },{"path": require("language_therapy/ressources/mot-image/autre/caméra.jpg"),
                "fr": "caméra",
                "ar": "كاميرا"
              },{"path": require("language_therapy/ressources/mot-image/autre/cartes.jpg"),
                "fr": "cartes",
                "ar": "شدة"
              },{"path": require("language_therapy/ressources/mot-image/autre/casque.jpg"),
                "fr": "casque",
                "ar": "خوذة"
              },{"path": require("language_therapy/ressources/mot-image/autre/casserole.jpg"),
                "fr": "casserole",
                "ar": "وعاء طهي"
              },{"path": require("language_therapy/ressources/mot-image/autre/ceinture.jpg"),
                "fr": "ceinture",
                "ar": "حزام"
              },{"path": require("language_therapy/ressources/mot-image/autre/cerveau.jpg"),
                "fr": "cerveau",
                "ar": "دماغ"
              },{"path": require("language_therapy/ressources/mot-image/autre/chaise.jpg"),
                "fr": "chaise",
                "ar": "كرسي"
              },{"path": require("language_therapy/ressources/mot-image/autre/chapeau.jpg"),
                "fr": "chapeau",
                "ar": "قبعة"
              },{"path": require("language_therapy/ressources/mot-image/autre/chaussure.jpg"),
                "fr": "chaussure",
                "ar": "حذاء"
              },{"path": require("language_therapy/ressources/mot-image/autre/chemise.jpg"),
                "fr": "chemise",
                "ar": "قميص"
              },{"path": require("language_therapy/ressources/mot-image/autre/ciseaux.jpg"),
                "fr": "ciseaux",
                "ar": "مقص"
              },{"path": require("language_therapy/ressources/mot-image/autre/clé.jpg"),
                "fr": "clé",
                "ar": "مفتاح"
              },{"path": require("language_therapy/ressources/mot-image/autre/couteau.jpg"),
                "fr": "couteau",
                "ar": "سكين"
              },{"path": require("language_therapy/ressources/mot-image/autre/cuillère.jpg"),
                "fr": "cuillère",
                "ar": "ملعقة"
              },{"path": require("language_therapy/ressources/mot-image/autre/dés.jpg"),
                "fr": "dés",
                "ar": "النرد"
              },{"path": require("language_therapy/ressources/mot-image/autre/echarpe.jpg"),
                "fr": "echarpe",
                "ar": "وشاح"
              },{"path": require("language_therapy/ressources/mot-image/autre/enveloppe.jpg"),
                "fr": "enveloppe",
                "ar": "مظروف"
              },{"path": require("language_therapy/ressources/mot-image/autre/fauteuil.jpg"),
                "fr": "fauteuil",
                "ar": "أريكة"
              },{"path": require("language_therapy/ressources/mot-image/autre/fleur.jpg"),
                "fr": "fleur",
                "ar": "زهرة"
              },{"path": require("language_therapy/ressources/mot-image/autre/fourchette.jpg"),
                "fr": "fourchette",
                "ar": "شوكة"
              },{"path": require("language_therapy/ressources/mot-image/autre/gomme.jpg"),
                "fr": "gomme",
                "ar": "ممحاة"
              },{"path": require("language_therapy/ressources/mot-image/autre/guitare.jpg"),
                "fr": "guitare",
                "ar": "غيتار"
              },{"path": require("language_therapy/ressources/mot-image/autre/horloge.jpg"),
                "fr": "horloge",
                "ar": "الساعة"
              },{"path": require("language_therapy/ressources/mot-image/autre/lait.jpg"),
                "fr": "lait",
                "ar": "حليب"
              },{"path": require("language_therapy/ressources/mot-image/autre/lampe.jpg"),
                "fr": "lampe",
                "ar": "مصباح"
              },{"path": require("language_therapy/ressources/mot-image/autre/lit.jpg"),
                "fr": "lit",
                "ar": "سرير"
              },{"path": require("language_therapy/ressources/mot-image/autre/lunettes.jpg"),
                "fr": "lunettes",
                "ar": "نظارات"
              },{"path": require("language_therapy/ressources/mot-image/autre/marteau.jpg"),
                "fr": "marteau",
                "ar": "مطرقة"
              },{"path": require("language_therapy/ressources/mot-image/autre/montagne.jpg"),
                "fr": "montagne",
                "ar": "جبل"
              },{"path": require("language_therapy/ressources/mot-image/autre/montre.jpg"),
                "fr": "montre",
                "ar": "ساعة"
              },{"path": require("language_therapy/ressources/mot-image/autre/nuage.jpg"),
                "fr": "nuage",
                "ar": "غيم"
              },{"path": require("language_therapy/ressources/mot-image/autre/ordinateur.jpg"),
                "fr": "ordinateur",
                "ar": "الكمبيوتر"
              },{"path": require("language_therapy/ressources/mot-image/autre/panier.jpg"),
                "fr": "panier",
                "ar": "سلة"
              },{"path": require("language_therapy/ressources/mot-image/autre/pansement.jpg"),
                "fr": "pansement",
                "ar": "صلصة"
              },{"path": require("language_therapy/ressources/mot-image/autre/pantalon.jpg"),
                "fr": "pantalon",
                "ar": "بنطلون"
              },{"path": require("language_therapy/ressources/mot-image/autre/peigne.jpg"),
                "fr": "peigne",
                "ar": "مشط"
              },{"path": require("language_therapy/ressources/mot-image/autre/plage.jpg"),
                "fr": "plage",
                "ar": "شاطئ"
              },{"path": require("language_therapy/ressources/mot-image/autre/poele.jpg"),
                "fr": "poele",
                "ar": "موقد"
              },{"path": require("language_therapy/ressources/mot-image/autre/porte.jpg"),
                "fr": "porte",
                "ar": "باب"
              },{"path": require("language_therapy/ressources/mot-image/autre/pull.jpg"),
                "fr": "pull",
                "ar": "سترة"
              },{"path": require("language_therapy/ressources/mot-image/autre/raquette.jpg"),
                "fr": "raquette",
                "ar": "مضرب"
              },{"path": require("language_therapy/ressources/mot-image/autre/rasoir.jpg"),
                "fr": "rasoir",
                "ar": "ماكينة حلاقة"
              },{"path": require("language_therapy/ressources/mot-image/autre/sac.jpg"),
                "fr": "sac",
                "ar": "حقيبة"
              },{"path": require("language_therapy/ressources/mot-image/autre/scie.jpg"),
                "fr": "scie",
                "ar": "منشار"
              },{"path": require("language_therapy/ressources/mot-image/autre/stylo.jpg"),
                "fr": "stylo",
                "ar": "قلم"
              },{"path": require("language_therapy/ressources/mot-image/autre/table.jpg"),
                "fr": "table",
                "ar": "حقيبة"
              },{"path": require("language_therapy/ressources/mot-image/autre/tente.jpg"),
                "fr": "tente",
                "ar": "خيمة"
              },{"path": require("language_therapy/ressources/mot-image/autre/thermometre.jpg"),
                "fr": "thermometre",
                "ar": "ميزان الحرارة"
              },{"path": require("language_therapy/ressources/mot-image/autre/théière.jpg"),
                "fr": "théière",
                "ar": "إبريق"
              },{"path": require("language_therapy/ressources/mot-image/autre/train.jpg"),
                "fr": "train",
                "ar": "قطار"
              },{"path": require("language_therapy/ressources/mot-image/autre/téléphone.jpg"),
                "fr": "téléphone",
                "ar": "هاتف"
              },{"path": require("language_therapy/ressources/mot-image/autre/télévision.jpg"),
                "fr": "télévision",
                "ar": "التلفزيون"
              },{"path": require("language_therapy/ressources/mot-image/autre/valise.jpg"),
                "fr": "valise",
                "ar": "حقيبة"
              },{"path": require("language_therapy/ressources/mot-image/autre/verre.jpg"),
                "fr": "verre",
                "ar": "زجاج"
              },{"path": require("language_therapy/ressources/mot-image/autre/voiture.jpg"),
                "fr": "voiture",
                "ar": "سيارة"
              },{"path": require("language_therapy/ressources/mot-image/autre/vélo.jpg"),
                "fr": "vélo",
                "ar": "دراجة"
              },{"path": require("language_therapy/ressources/mot-image/autre/évier.jpg"),
                "fr": "évier",
                "ar": "حوض الغسيل"
              }],"recette-arabe":[{"path": require("language_therapy/ressources/mot-image/recette-arabe/bami.jpg"),
                "fr": "bami",
                "ar": "بامية"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/falafel.jpg"),
                "fr": "falafel",
                "ar": "فلافل"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/fatouche.jpg"),
                "fr": "fatouche",
                "ar": "فتوش"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/houmous.jpg"),
                "fr": "houmous",
                "ar": "الحمص"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/kebbeh_cru.jpg"),
                "fr": "kebbeh cru",
                "ar": "الكبة"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/kebbeh_frit.jpg"),
                "fr": "kebbeh frit",
                "ar": "الكبة"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/kebbe_bel_fern.jpg"),
                "fr": "kebbe bel fern",
                "ar": "الكبة"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/malfouf.jpg"),
                "fr": "malfouf",
                "ar": "ملفوف"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/mehshi.jpg"),
                "fr": "mehshi",
                "ar": "محشي"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/moujadra.jpg"),
                "fr": "moujadra",
                "ar": "مجدرة"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/namoura.jpg"),
                "fr": "namoura",
                "ar": "نمورت"
              },{"path": require("language_therapy/ressources/mot-image/recette-arabe/taboule.jpg"),
                "fr": "taboule",
                "ar": "تبوله"
              }],};export default {_IMAGES }