let _IMAGES = {
	"aliments": [{
			"path": require("language_therapy/ressources/mot-image/aliments/abricot-مشمش.jpg"),
			"fr": "abricot",
			"ar": "مشمش"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/ail-ثوم.jpg"),
			"fr": "ail",
			"ar": "ثوم"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/amande-لوز.jpg"),
			"fr": "amande",
			"ar": "لوز"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/ananas-أناناس.jpg"),
			"fr": "ananas",
			"ar": "أناناس"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/aubergine-باذنجان.jpg"),
			"fr": "aubergine",
			"ar": "باذنجان"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/baguette-خبز.jpg"),
			"fr": "baguette",
			"ar": "خبز"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/banane-موز.jpg"),
			"fr": "banane",
			"ar": "موز"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/beurre-زبدة.jpg"),
			"fr": "beurre",
			"ar": "زبدة"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/carotte-جزرة.jpg"),
			"fr": "carotte",
			"ar": "جزرة"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/cerise-الكرز.jpg"),
			"fr": "cerise",
			"ar": "الكرز"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/champignon-فطر.jpg"),
			"fr": "champignon",
			"ar": "فطر"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/chocolat-شوكولا.jpg"),
			"fr": "chocolat",
			"ar": "شوكولا"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/choux_fleur-ملفوف.jpg"),
			"fr": "choux fleur",
			"ar": "ملفوف"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/citron-ليمون.jpg"),
			"fr": "citron",
			"ar": "ليمون"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/courgette-كوسا.jpg"),
			"fr": "courgette",
			"ar": "كوسا"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/figue-تين.jpg"),
			"fr": "figue",
			"ar": "تين"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/fraise-فراولة.jpg"),
			"fr": "fraise",
			"ar": "فراولة"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/grenade-رمان.jpg"),
			"fr": "grenade",
			"ar": "رمان"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/haricot_vert-الفاصوليا.jpg"),
			"fr": "haricot vert",
			"ar": "الفاصوليا"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/miel-عسل.jpg"),
			"fr": "miel",
			"ar": "عسل"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/noix-جوز.jpg"),
			"fr": "noix",
			"ar": "جوز"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/oeuf-بيضة.jpg"),
			"fr": "oeuf",
			"ar": "بيضة"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/oignon-بصل.jpg"),
			"fr": "oignon",
			"ar": "بصل"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/orange-برتقال.jpg"),
			"fr": "orange",
			"ar": "برتقال"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/pastèque-بطيخ.jpg"),
			"fr": "pastèque",
			"ar": "بطيخ"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/pates-معكرونة.jpg"),
			"fr": "pates",
			"ar": "معكرونة"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/poire-اجاصة.jpg"),
			"fr": "poire",
			"ar": "اجاصة"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/poivron-فلفل_حلو.jpg"),
			"fr": "poivron",
			"ar": "فلفل حلو"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/pomme-تفاح.jpg"),
			"fr": "pomme",
			"ar": "تفاح"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/pomme_de_terre-بطاطا.jpg"),
			"fr": "pomme de terre",
			"ar": "بطاطا"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/radis-فجل.jpg"),
			"fr": "radis",
			"ar": "فجل"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/raisin-عنب.jpg"),
			"fr": "raisin",
			"ar": "عنب"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/riz-الرز.jpg"),
			"fr": "riz",
			"ar": "الرز"
		}, {
			"path": require("language_therapy/ressources/mot-image/aliments/tomate-بندورة_.jpg"),
			"fr": "tomate",
			"ar": "بندورة "
		}
	],
	"animaux": [{
			"path": require("language_therapy/ressources/mot-image/animaux/canard-بطة.jpg"),
			"fr": "canard",
			"ar": "بطة"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/chat-قطة.jpg"),
			"fr": "chat",
			"ar": "قطة"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/cheval-حصان.jpg"),
			"fr": "cheval",
			"ar": "حصان"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/chien-كلب.jpg"),
			"fr": "chien",
			"ar": "كلب"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/chèvre-معزاة.jpg"),
			"fr": "chèvre",
			"ar": "معزاة"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/colombe-حمام.jpg"),
			"fr": "colombe",
			"ar": "حمام"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/crocodile-تمساح.jpg"),
			"fr": "crocodile",
			"ar": "تمساح"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/cygne-وزة.jpg"),
			"fr": "cygne",
			"ar": "وزة"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/girafe-زرافة.jpg"),
			"fr": "girafe",
			"ar": "زرافة"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/lapin-أرنب.jpg"),
			"fr": "lapin",
			"ar": "أرنب"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/lion-اسد.jpg"),
			"fr": "lion",
			"ar": "اسد"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/loup-ذئب.jpg"),
			"fr": "loup",
			"ar": "ذئب"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/lézard-حرباء.jpg"),
			"fr": "lézard",
			"ar": "حرباء"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/mouton-خاروف.jpg"),
			"fr": "mouton",
			"ar": "خاروف"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/ours-دب.jpg"),
			"fr": "ours",
			"ar": "دب"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/pingouin-بطريق.jpg"),
			"fr": "pingouin",
			"ar": "بطريق"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/poisson_rouge-سمكة_حمراء.jpg"),
			"fr": "poisson rouge",
			"ar": "سمكة حمراء"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/poule-دجاجة.jpg"),
			"fr": "poule",
			"ar": "دجاجة"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/serpent-أفعى.jpg"),
			"fr": "serpent",
			"ar": "أفعى"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/souris-فأر.jpg"),
			"fr": "souris",
			"ar": "فأر"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/tigre-نمر.jpg"),
			"fr": "tigre",
			"ar": "نمر"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/vache-بقرة.jpg"),
			"fr": "vache",
			"ar": "بقرة"
		}, {
			"path": require("language_therapy/ressources/mot-image/animaux/éléphant-فيل.jpg"),
			"fr": "éléphant",
			"ar": "فيل"
		}
	],
	"autre": [{
			"path": require("language_therapy/ressources/mot-image/autre/allumette-كبريتة.jpg"),
			"fr": "allumette",
			"ar": "كبريتة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/arbre-شجره.jpg"),
			"fr": "arbre",
			"ar": "شجره"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/aspirateur-مكنسة_كهربائية.jpg"),
			"fr": "aspirateur",
			"ar": "مكنسة كهربائية"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/assiette-صحن.jpg"),
			"fr": "assiette",
			"ar": "صحن"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/avion-طائرة.jpg"),
			"fr": "avion",
			"ar": "طائرة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/bague-خاتم.jpg"),
			"fr": "bague",
			"ar": "خاتم"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/balai-مكنسة.jpg"),
			"fr": "balai",
			"ar": "مكنسة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/balançoire-أرجوحة.jpg"),
			"fr": "balançoire",
			"ar": "أرجوحة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/ballon-كرة.jpg"),
			"fr": "ballon",
			"ar": "كرة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/bateau-قارب.jpg"),
			"fr": "bateau",
			"ar": "قارب"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/bonnet-قبعة.jpg"),
			"fr": "bonnet",
			"ar": "قبعة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/bouteille-زجاجة.jpg"),
			"fr": "bouteille",
			"ar": "زجاجة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/boîte-ساعة.jpg"),
			"fr": "boîte",
			"ar": "ساعة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/briquet-ولاعة.jpg"),
			"fr": "briquet",
			"ar": "ولاعة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/brosse_à_dent-فرشاة_أسنان.jpg"),
			"fr": "brosse à dent",
			"ar": "فرشاة أسنان"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/bus-الباص.jpg"),
			"fr": "bus",
			"ar": "الباص"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/café-قهوة.jpg"),
			"fr": "café",
			"ar": "قهوة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/camion-شاحنة.jpg"),
			"fr": "camion",
			"ar": "شاحنة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/caméra-كاميرا.jpg"),
			"fr": "caméra",
			"ar": "كاميرا"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/cartes-شدة.jpg"),
			"fr": "cartes",
			"ar": "شدة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/casque-خوذة.jpg"),
			"fr": "casque",
			"ar": "خوذة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/casserole-وعاء_طهي.jpg"),
			"fr": "casserole",
			"ar": "وعاء طهي"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/ceinture-حزام.jpg"),
			"fr": "ceinture",
			"ar": "حزام"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/cerveau-دماغ.jpg"),
			"fr": "cerveau",
			"ar": "دماغ"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/chaise-كرسي.jpg"),
			"fr": "chaise",
			"ar": "كرسي"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/chapeau-قبعة.jpg"),
			"fr": "chapeau",
			"ar": "قبعة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/chaussure-حذاء.jpg"),
			"fr": "chaussure",
			"ar": "حذاء"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/chemise-قميص.jpg"),
			"fr": "chemise",
			"ar": "قميص"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/ciseaux-مقص.jpg"),
			"fr": "ciseaux",
			"ar": "مقص"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/clé-مفتاح.jpg"),
			"fr": "clé",
			"ar": "مفتاح"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/couteau-سكين.jpg"),
			"fr": "couteau",
			"ar": "سكين"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/cuillère-ملعقة.jpg"),
			"fr": "cuillère",
			"ar": "ملعقة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/dés-النرد.jpg"),
			"fr": "dés",
			"ar": "النرد"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/echarpe-وشاح.jpg"),
			"fr": "echarpe",
			"ar": "وشاح"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/enveloppe-مظروف.jpg"),
			"fr": "enveloppe",
			"ar": "مظروف"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/fauteuil-أريكة.jpg"),
			"fr": "fauteuil",
			"ar": "أريكة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/fleur-زهرة.jpg"),
			"fr": "fleur",
			"ar": "زهرة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/fourchette-شوكة.jpg"),
			"fr": "fourchette",
			"ar": "شوكة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/gomme-ممحاة.jpg"),
			"fr": "gomme",
			"ar": "ممحاة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/guitare-غيتار.jpg"),
			"fr": "guitare",
			"ar": "غيتار"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/horloge-الساعة.jpg"),
			"fr": "horloge",
			"ar": "الساعة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/lait-حليب.jpg"),
			"fr": "lait",
			"ar": "حليب"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/lampe-مصباح.jpg"),
			"fr": "lampe",
			"ar": "مصباح"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/lit-سرير.jpg"),
			"fr": "lit",
			"ar": "سرير"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/lunettes-نظارات.jpg"),
			"fr": "lunettes",
			"ar": "نظارات"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/marteau-مطرقة.jpg"),
			"fr": "marteau",
			"ar": "مطرقة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/montagne-جبل.jpg"),
			"fr": "montagne",
			"ar": "جبل"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/montre-ساعة.jpg"),
			"fr": "montre",
			"ar": "ساعة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/nuage-غيم.jpg"),
			"fr": "nuage",
			"ar": "غيم"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/ordinateur-الكمبيوتر.jpg"),
			"fr": "ordinateur",
			"ar": "الكمبيوتر"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/panier-سلة.jpg"),
			"fr": "panier",
			"ar": "سلة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/pansement-صلصة.jpg"),
			"fr": "pansement",
			"ar": "صلصة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/pantalon-بنطلون.jpg"),
			"fr": "pantalon",
			"ar": "بنطلون"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/peigne-مشط.jpg"),
			"fr": "peigne",
			"ar": "مشط"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/plage-شاطئ.jpg"),
			"fr": "plage",
			"ar": "شاطئ"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/poele-موقد.jpg"),
			"fr": "poele",
			"ar": "موقد"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/porte-باب.jpg"),
			"fr": "porte",
			"ar": "باب"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/pull-سترة.jpg"),
			"fr": "pull",
			"ar": "سترة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/raquette-مضرب.jpg"),
			"fr": "raquette",
			"ar": "مضرب"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/rasoir-ماكينة_حلاقة.jpg"),
			"fr": "rasoir",
			"ar": "ماكينة حلاقة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/sac-حقيبة.jpg"),
			"fr": "sac",
			"ar": "حقيبة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/scie-منشار.jpg"),
			"fr": "scie",
			"ar": "منشار"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/stylo-قلم.jpg"),
			"fr": "stylo",
			"ar": "قلم"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/table-حقيبة.jpg"),
			"fr": "table",
			"ar": "حقيبة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/tente-خيمة.jpg"),
			"fr": "tente",
			"ar": "خيمة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/thermometre-ميزان_الحرارة.jpg"),
			"fr": "thermometre",
			"ar": "ميزان الحرارة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/théière-إبريق.jpg"),
			"fr": "théière",
			"ar": "إبريق"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/train-قطار.jpg"),
			"fr": "train",
			"ar": "قطار"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/téléphone-هاتف.jpg"),
			"fr": "téléphone",
			"ar": "هاتف"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/télévision-التلفزيون.jpg"),
			"fr": "télévision",
			"ar": "التلفزيون"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/valise-حقيبة.jpg"),
			"fr": "valise",
			"ar": "حقيبة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/verre-زجاج.jpg"),
			"fr": "verre",
			"ar": "زجاج"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/voiture-سيارة.jpg"),
			"fr": "voiture",
			"ar": "سيارة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/vélo-دراجة.jpg"),
			"fr": "vélo",
			"ar": "دراجة"
		}, {
			"path": require("language_therapy/ressources/mot-image/autre/évier-حوض_الغسيل.jpg"),
			"fr": "évier",
			"ar": "حوض الغسيل"
		}
	],
	"recette-arabe": [{
			"path": require("language_therapy/ressources/mot-image/recette-arabe/bami-بامية.jpg"),
			"fr": "bami",
			"ar": "بامية"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/falafel-فلافل.jpg"),
			"fr": "falafel",
			"ar": "فلافل"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/fatouche-فتوش.jpg"),
			"fr": "fatouche",
			"ar": "فتوش"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/houmous-الحمص.jpg"),
			"fr": "houmous",
			"ar": "الحمص"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/kebbeh_cru-الكبة.jpg"),
			"fr": "kebbeh cru",
			"ar": "الكبة"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/kebbeh_frit-الكبة.jpg"),
			"fr": "kebbeh frit",
			"ar": "الكبة"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/kebbe_bel_fern-الكبة.jpg"),
			"fr": "kebbe bel fern",
			"ar": "الكبة"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/malfouf-ملفوف.jpg"),
			"fr": "malfouf",
			"ar": "ملفوف"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/mehshi-محشي.jpg"),
			"fr": "mehshi",
			"ar": "محشي"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/moujadra-مجدرة.jpg"),
			"fr": "moujadra",
			"ar": "مجدرة"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/namoura-نمورت.jpg"),
			"fr": "namoura",
			"ar": "نمورت"
		}, {
			"path": require("language_therapy/ressources/mot-image/recette-arabe/taboule-تبوله.jpg"),
			"fr": "taboule",
			"ar": "تبوله"
		}
	]
}
